const usersData = [
    {
      name: "John",
      surname: "Doe",
      email: "john.doe@example.com",
      phoneNumber: "123-456-7890",
      password: "password123",
      role: "admin",
      qualifications: "PhD in Computer Science",
      specialization: "Machine Learning",
      institution: "University A",
      assignedReviewers: ["Jane Smith", "Robert Brown"],
      assignedInstitutions: ["University B", "University C"],
      nextReviewDate: new Date("2024-07-01"),
      createdAt: new Date("2022-01-01"),
    },
    {
      name: "Jane",
      surname: "Smith",
      email: "jane.smith@example.com",
      phoneNumber: "987-654-3210",
      password: "password456",
      role: "reviewer",
      qualifications: "Master's in Chemistry",
      specialization: "Organic Chemistry",
      institution: "University B",
      nextReviewDate: new Date("2024-06-15"),
      createdAt: new Date("2022-02-01"),
    },
    {
      name: "Alice",
      surname: "Johnson",
      email: "alice.johnson@example.com",
      phoneNumber: "555-123-4567",
      password: "password789",
      role: "institution",
      institution: "University C",
      nextReviewDate: new Date("2024-06-30"),
      createdAt: new Date("2022-03-01"),
    },
    {
      name: "Robert",
      surname: "Brown",
      email: "robert.brown@example.com",
      phoneNumber: "444-987-6543",
      password: "password123",
      role: "superuser",
      nextReviewDate: new Date("2024-06-25"),
      createdAt: new Date("2022-04-01"),
    },
  ];
  
  export default usersData;
  